name: React Native Learning

on:
  push:
    branches:
      - master
      - '**'
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run test
      - run: npm run lint
  build_android:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      EXPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm install -g eas-cli
      - run: eas login --token ${{secrets.EXPO_TOKEN}}
      - run: eas build --platform android
      - run: echo 'EXPO_TOKEN'